// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package i9e

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CrRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsCrRequest(buf []byte, offset flatbuffers.UOffsetT) *CrRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CrRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *CrRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CrRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CrRequest) ReqType() CreatorReqMsg {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return CreatorReqMsg(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *CrRequest) MutateReqType(n CreatorReqMsg) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *CrRequest) Req(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func CrRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CrRequestAddReqType(builder *flatbuffers.Builder, reqType CreatorReqMsg) {
	builder.PrependByteSlot(0, byte(reqType), 0)
}
func CrRequestAddReq(builder *flatbuffers.Builder, req flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(req), 0)
}
func CrRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
