// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package i9e

import "strconv"

type GameEventType int8

const (
	GameEventTypeGameStarted     GameEventType = 0
	GameEventTypeWin             GameEventType = 1
	GameEventTypeTie             GameEventType = 2
	GameEventTypeOK              GameEventType = 3
	GameEventTypeCheating        GameEventType = 4
	GameEventTypeOppCheating     GameEventType = 5
	GameEventTypeDisonnected     GameEventType = 6
	GameEventTypeOppDisconnected GameEventType = 7
)

var EnumNamesGameEventType = map[GameEventType]string{
	GameEventTypeGameStarted:     "GameStarted",
	GameEventTypeWin:             "Win",
	GameEventTypeTie:             "Tie",
	GameEventTypeOK:              "OK",
	GameEventTypeCheating:        "Cheating",
	GameEventTypeOppCheating:     "OppCheating",
	GameEventTypeDisonnected:     "Disonnected",
	GameEventTypeOppDisconnected: "OppDisconnected",
}

var EnumValuesGameEventType = map[string]GameEventType{
	"GameStarted":     GameEventTypeGameStarted,
	"Win":             GameEventTypeWin,
	"Tie":             GameEventTypeTie,
	"OK":              GameEventTypeOK,
	"Cheating":        GameEventTypeCheating,
	"OppCheating":     GameEventTypeOppCheating,
	"Disonnected":     GameEventTypeDisonnected,
	"OppDisconnected": GameEventTypeOppDisconnected,
}

func (v GameEventType) String() string {
	if s, ok := EnumNamesGameEventType[v]; ok {
		return s
	}
	return "GameEventType(" + strconv.FormatInt(int64(v), 10) + ")"
}
