// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package i9e

import "strconv"

type MarkType int8

const (
	MarkTypeCross  MarkType = 0
	MarkTypeNought MarkType = 1
)

var EnumNamesMarkType = map[MarkType]string{
	MarkTypeCross:  "Cross",
	MarkTypeNought: "Nought",
}

var EnumValuesMarkType = map[string]MarkType{
	"Cross":  MarkTypeCross,
	"Nought": MarkTypeNought,
}

func (v MarkType) String() string {
	if s, ok := EnumNamesMarkType[v]; ok {
		return s
	}
	return "MarkType(" + strconv.FormatInt(int64(v), 10) + ")"
}
