// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package i9e

import "strconv"

type MarkTypeFilter int8

const (
	MarkTypeFilterCross  MarkTypeFilter = 0
	MarkTypeFilterNought MarkTypeFilter = 1
	MarkTypeFilterAny    MarkTypeFilter = 2
)

var EnumNamesMarkTypeFilter = map[MarkTypeFilter]string{
	MarkTypeFilterCross:  "Cross",
	MarkTypeFilterNought: "Nought",
	MarkTypeFilterAny:    "Any",
}

var EnumValuesMarkTypeFilter = map[string]MarkTypeFilter{
	"Cross":  MarkTypeFilterCross,
	"Nought": MarkTypeFilterNought,
	"Any":    MarkTypeFilterAny,
}

func (v MarkTypeFilter) String() string {
	if s, ok := EnumNamesMarkTypeFilter[v]; ok {
		return s
	}
	return "MarkTypeFilter(" + strconv.FormatInt(int64(v), 10) + ")"
}
