// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package i9e

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Move struct {
	_tab flatbuffers.Table
}

func GetRootAsMove(buf []byte, offset flatbuffers.UOffsetT) *Move {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Move{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Move) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Move) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Move) Row() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Move) MutateRow(n int16) bool {
	return rcv._tab.MutateInt16Slot(4, n)
}

func (rcv *Move) Col() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Move) MutateCol(n int16) bool {
	return rcv._tab.MutateInt16Slot(6, n)
}

func MoveStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MoveAddRow(builder *flatbuffers.Builder, row int16) {
	builder.PrependInt16Slot(0, row, 0)
}
func MoveAddCol(builder *flatbuffers.Builder, col int16) {
	builder.PrependInt16Slot(1, col, 0)
}
func MoveEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
