// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package i9e

import "strconv"

type OpponentReqMsg byte

const (
	OpponentReqMsgNONE   OpponentReqMsg = 0
	OpponentReqMsgGameId OpponentReqMsg = 1
	OpponentReqMsgMove   OpponentReqMsg = 2
)

var EnumNamesOpponentReqMsg = map[OpponentReqMsg]string{
	OpponentReqMsgNONE:   "NONE",
	OpponentReqMsgGameId: "GameId",
	OpponentReqMsgMove:   "Move",
}

var EnumValuesOpponentReqMsg = map[string]OpponentReqMsg{
	"NONE":   OpponentReqMsgNONE,
	"GameId": OpponentReqMsgGameId,
	"Move":   OpponentReqMsgMove,
}

func (v OpponentReqMsg) String() string {
	if s, ok := EnumNamesOpponentReqMsg[v]; ok {
		return s
	}
	return "OpponentReqMsg(" + strconv.FormatInt(int64(v), 10) + ")"
}
