// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package i9e

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OppResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsOppResponse(buf []byte, offset flatbuffers.UOffsetT) *OppResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OppResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *OppResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OppResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OppResponse) RespType() OpponentRespMsg {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return OpponentRespMsg(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *OppResponse) MutateRespType(n OpponentRespMsg) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *OppResponse) Resp(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func OppResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func OppResponseAddRespType(builder *flatbuffers.Builder, respType OpponentRespMsg) {
	builder.PrependByteSlot(0, byte(respType), 0)
}
func OppResponseAddResp(builder *flatbuffers.Builder, resp flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(resp), 0)
}
func OppResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
