// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package transport

import "strconv"

type CreatorRespMsg byte

const (
	CreatorRespMsgNONE      CreatorRespMsg = 0
	CreatorRespMsgMove      CreatorRespMsg = 1
	CreatorRespMsgGameId    CreatorRespMsg = 2
	CreatorRespMsgGameEvent CreatorRespMsg = 3
)

var EnumNamesCreatorRespMsg = map[CreatorRespMsg]string{
	CreatorRespMsgNONE:      "NONE",
	CreatorRespMsgMove:      "Move",
	CreatorRespMsgGameId:    "GameId",
	CreatorRespMsgGameEvent: "GameEvent",
}

var EnumValuesCreatorRespMsg = map[string]CreatorRespMsg{
	"NONE":      CreatorRespMsgNONE,
	"Move":      CreatorRespMsgMove,
	"GameId":    CreatorRespMsgGameId,
	"GameEvent": CreatorRespMsgGameEvent,
}

func (v CreatorRespMsg) String() string {
	if s, ok := EnumNamesCreatorRespMsg[v]; ok {
		return s
	}
	return "CreatorRespMsg(" + strconv.FormatInt(int64(v), 10) + ")"
}
