// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package transport

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CrResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsCrResponse(buf []byte, offset flatbuffers.UOffsetT) *CrResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CrResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *CrResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CrResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CrResponse) RespType() CreatorRespMsg {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return CreatorRespMsg(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *CrResponse) MutateRespType(n CreatorRespMsg) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *CrResponse) Resp(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func CrResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CrResponseAddRespType(builder *flatbuffers.Builder, respType CreatorRespMsg) {
	builder.PrependByteSlot(0, byte(respType), 0)
}
func CrResponseAddResp(builder *flatbuffers.Builder, resp flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(resp), 0)
}
func CrResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
