// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package transport

import "strconv"

type FollowUpMessage byte

const (
	FollowUpMessageNONE    FollowUpMessage = 0
	FollowUpMessageWinLine FollowUpMessage = 1
)

var EnumNamesFollowUpMessage = map[FollowUpMessage]string{
	FollowUpMessageNONE:    "NONE",
	FollowUpMessageWinLine: "WinLine",
}

var EnumValuesFollowUpMessage = map[string]FollowUpMessage{
	"NONE":    FollowUpMessageNONE,
	"WinLine": FollowUpMessageWinLine,
}

func (v FollowUpMessage) String() string {
	if s, ok := EnumNamesFollowUpMessage[v]; ok {
		return s
	}
	return "FollowUpMessage(" + strconv.FormatInt(int64(v), 10) + ")"
}
