// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package transport

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GamesList struct {
	_tab flatbuffers.Table
}

func GetRootAsGamesList(buf []byte, offset flatbuffers.UOffsetT) *GamesList {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GamesList{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *GamesList) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GamesList) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GamesList) Items(obj *ListItem, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *GamesList) ItemsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func GamesListStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GamesListAddItems(builder *flatbuffers.Builder, items flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(items), 0)
}
func GamesListStartItemsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func GamesListEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
