// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package transport

import "strconv"

type OpponentRespMsg byte

const (
	OpponentRespMsgNONE      OpponentRespMsg = 0
	OpponentRespMsgMove      OpponentRespMsg = 1
	OpponentRespMsgGameEvent OpponentRespMsg = 2
)

var EnumNamesOpponentRespMsg = map[OpponentRespMsg]string{
	OpponentRespMsgNONE:      "NONE",
	OpponentRespMsgMove:      "Move",
	OpponentRespMsgGameEvent: "GameEvent",
}

var EnumValuesOpponentRespMsg = map[string]OpponentRespMsg{
	"NONE":      OpponentRespMsgNONE,
	"Move":      OpponentRespMsgMove,
	"GameEvent": OpponentRespMsgGameEvent,
}

func (v OpponentRespMsg) String() string {
	if s, ok := EnumNamesOpponentRespMsg[v]; ok {
		return s
	}
	return "OpponentRespMsg(" + strconv.FormatInt(int64(v), 10) + ")"
}
